/** Asia-Pacific countries and territories for Help Desk selection */

export const ASIA_PACIFIC_LOCATIONS = [
  'Australia',
  'Bangladesh',
  'Bhutan',
  'Brunei',
  'Cambodia',
  'Cook Islands',
  'Fiji',
  'French Polynesia',
  'Guam',
  'Hong Kong (China)',
  'India',
  'Indonesia',
  'Japan',
  'Kiribati',
  'Laos',
  'Macau (China)',
  'Mainland China',
  'Malaysia',
  'Maldives',
  'Marshall Islands',
  'Micronesia',
  'Mongolia',
  'Myanmar',
  'Nauru',
  'Nepal',
  'New Caledonia',
  'New Zealand',
  'Niue',
  'Pakistan',
  'Palau',
  'Papua New Guinea',
  'Philippines',
  'Samoa',
  'Singapore',
  'Solomon Islands',
  'South Korea',
  'Sri Lanka',
  'Taiwan (China)',
  'Thailand',
  'Timor-Leste',
  'Tonga',
  'Tuvalu',
  'Vanuatu',
  'Vietnam',
] as const;

export type AsiaPacificLocation = (typeof ASIA_PACIFIC_LOCATIONS)[number];
