import type { DirectoryEntry, Resource, Campaign } from "./types";

// Mock Directory Entries for Organics
export const DIRECTORY_ENTRIES: DirectoryEntry[] = [
  {
    id: "1",
    name: "Manila Composting Facility",
    type: "facility",
    tags: ["organics"],
    location: {
      lat: 14.5995,
      lng: 120.9842,
      city: "Manila",
      country: "Philippines",
    },
    summary: "Community composting facility processing 50 tonnes of organic waste monthly",
    website: "https://example.com/manila-compost",
    verified: true,
  },
  {
    id: "2",
    name: "Jakarta Green Waste Initiative",
    type: "initiative",
    tags: ["organics", "reduction"],
    location: {
      lat: -6.2088,
      lng: 106.8456,
      city: "Jakarta",
      country: "Indonesia",
    },
    summary: "Urban organic waste collection and processing program serving 10,000 households",
    website: "https://example.com/jakarta-green",
    verified: true,
  },
  {
    id: "3",
    name: "Bangkok Urban Farmers Network",
    type: "organization",
    tags: ["organics"],
    location: {
      lat: 13.7563,
      lng: 100.5018,
      city: "Bangkok",
      country: "Thailand",
    },
    summary: "Network of urban farmers converting food waste into compost for community gardens",
    verified: false,
  },
  {
    id: "4",
    name: "Singapore Food Waste Digester",
    type: "facility",
    tags: ["organics"],
    location: {
      lat: 1.3521,
      lng: 103.8198,
      city: "Singapore",
      country: "Singapore",
    },
    summary: "Industrial anaerobic digestion facility processing 100 tonnes daily",
    website: "https://example.com/singapore-digester",
    verified: true,
  },
  {
    id: "5",
    name: "Hanoi Organic Collection Program",
    type: "initiative",
    tags: ["organics", "reduction"],
    location: {
      lat: 21.0285,
      lng: 105.8542,
      city: "Hanoi",
      country: "Vietnam",
    },
    summary: "Door-to-door organic waste collection serving residential areas",
    verified: true,
  },
  {
    id: "6",
    name: "Kuala Lumpur Composting Hub",
    type: "facility",
    tags: ["organics"],
    location: {
      lat: 3.1390,
      lng: 101.6869,
      city: "Kuala Lumpur",
      country: "Malaysia",
    },
    summary: "Central composting facility with educational programs for schools",
    website: "https://example.com/kl-compost",
    verified: true,
  },
  {
    id: "7",
    name: "Cebu Zero Waste Coalition",
    type: "organization",
    tags: ["organics", "reduction", "policy"],
    location: {
      lat: 10.3157,
      lng: 123.8854,
      city: "Cebu",
      country: "Philippines",
    },
    summary: "Advocacy group promoting organic waste diversion policies",
    website: "https://example.com/cebu-zero-waste",
    verified: false,
  },
  {
    id: "8",
    name: "Bali Eco Warriors",
    type: "organization",
    tags: ["organics", "reuse"],
    location: {
      lat: -8.4095,
      lng: 115.1889,
      city: "Denpasar",
      country: "Indonesia",
    },
    summary: "Community organization running multiple composting centers across Bali",
    website: "https://example.com/bali-eco",
    verified: true,
  },
  {
    id: "9",
    name: "Phnom Penh Waste Solutions",
    type: "facility",
    tags: ["organics"],
    location: {
      lat: 11.5564,
      lng: 104.9282,
      city: "Phnom Penh",
      country: "Cambodia",
    },
    summary: "Mixed waste processing facility with organic separation line",
    verified: false,
  },
  {
    id: "10",
    name: "Taipei Circular Economy Hub",
    type: "initiative",
    tags: ["organics", "reduction"],
    location: {
      lat: 25.0330,
      lng: 121.5654,
      city: "Taipei",
      country: "Taiwan",
    },
    summary: "Government initiative promoting closed-loop organic waste systems",
    website: "https://example.com/taipei-circular",
    verified: true,
  },
];

// Mock Resources
export const RESOURCES: Resource[] = [
  {
    id: "1",
    slug: "back-to-earth",
    title: "Back to Earth",
    summary: "A comprehensive guide to composting organic waste at community scale",
    topics: ["organics"],
    publishDate: "2024-01-15",
    cover: "https://images.unsplash.com/photo-1572307480813-ceb0e59d8325?w=800&q=80",
    url: "https://example.com/back-to-earth",
    content: "Comprehensive content about composting methods, benefits, and implementation strategies...",
  },
  {
    id: "2",
    slug: "methane-matters",
    title: "Methane Matters: The Climate Case for Organics Diversion",
    summary: "Understanding the methane emissions from organic waste and climate impact",
    topics: ["organics", "policy"],
    publishDate: "2023-11-20",
    cover: "https://images.unsplash.com/photo-1569163139394-de4798aa62b6?w=800&q=80",
    content: "Detailed analysis of methane emissions from landfills and the climate benefits of composting...",
  },
  {
    id: "3",
    slug: "community-composting-toolkit",
    title: "Community Composting Toolkit",
    summary: "Step-by-step guide to starting a community composting program",
    topics: ["organics"],
    publishDate: "2024-02-10",
    cover: "https://images.unsplash.com/photo-1530836369250-ef72a3f5cda8?w=800&q=80",
    url: "https://example.com/toolkit",
    content: "Practical toolkit with templates, checklists, and best practices...",
  },
  {
    id: "4",
    slug: "asian-organics-landscape",
    title: "The State of Organic Waste Management in Asia",
    summary: "Regional analysis of organics management policies and practices",
    topics: ["organics", "policy"],
    publishDate: "2023-09-05",
    cover: "https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?w=800&q=80",
    content: "Comprehensive regional report covering 15 countries...",
  },
];

// Mock Campaign
export const METHANE_PLEDGE_CAMPAIGN: Campaign = {
  id: "methane-pledge",
  slug: "methane-pledge",
  title: "The Methane Pledge",
  summary: "Join cities, organizations, and individuals committed to reducing methane emissions from organic waste. Every tonne of organics diverted from landfills prevents 0.5 tonnes of CO₂-equivalent methane emissions.",
  ctaLabel: "Take the Pledge",
  ctaHref: "#pledge-form",
  stats: [
    { label: "Pledges Taken", value: 2847 },
    { label: "Organizations Joined", value: 142 },
    { label: "Estimated Annual CH₄ Avoided (tCO₂e)", value: 125000 },
    { label: "Countries Participating", value: 18 },
  ],
  faqs: [
    {
      question: "What is the Methane Pledge?",
      answer: "The Methane Pledge is a commitment by cities, organizations, and individuals to divert organic waste from landfills, reducing methane emissions. When organic waste decomposes in landfills without oxygen, it produces methane—a greenhouse gas 80+ times more potent than CO₂ over 20 years.",
    },
    {
      question: "Who can take the pledge?",
      answer: "Anyone! Individuals, households, businesses, organizations, and local governments are all welcome to take the pledge and commit to organic waste diversion through composting, anaerobic digestion, or other sustainable methods.",
    },
    {
      question: "How is methane avoided measured?",
      answer: "We use internationally recognized emission factors. For every tonne of organic waste diverted from landfills through composting or proper treatment, approximately 0.5 tonnes of CO₂-equivalent methane emissions are avoided. Your actual impact depends on local landfill conditions and diversion methods.",
    },
    {
      question: "What happens after I take the pledge?",
      answer: "You'll receive resources, toolkits, and updates on organic waste management best practices. You'll also be invited to share your progress and connect with others in the Zero Waste Asia community working toward the same goals.",
    },
  ],
};

