import type { DirectoryEntry, Resource, Campaign } from "./types";

// Mock Directory Entries for Organics
export const DIRECTORY_ENTRIES: DirectoryEntry[] = [
  {
    id: "1",
    name: "Manila Composting Facility",
    type: "facility",
    tags: ["organics"],
    location: {
      lat: 14.5995,
      lng: 120.9842,
      city: "Manila",
      country: "Philippines",
    },
    summary: "Community composting facility processing 50 tonnes of organic waste monthly",
    website: "https://example.com/manila-compost",
    verified: true,
  },
  {
    id: "2",
    name: "Jakarta Green Waste Initiative",
    type: "initiative",
    tags: ["organics", "reduction"],
    location: {
      lat: -6.2088,
      lng: 106.8456,
      city: "Jakarta",
      country: "Indonesia",
    },
    summary: "Urban organic waste collection and processing program serving 10,000 households",
    website: "https://example.com/jakarta-green",
    verified: true,
  },
  {
    id: "3",
    name: "Bangkok Urban Farmers Network",
    type: "organization",
    tags: ["organics"],
    location: {
      lat: 13.7563,
      lng: 100.5018,
      city: "Bangkok",
      country: "Thailand",
    },
    summary: "Network of urban farmers converting food waste into compost for community gardens",
    verified: false,
  },
  {
    id: "4",
    name: "Singapore Food Waste Digester",
    type: "facility",
    tags: ["organics"],
    location: {
      lat: 1.3521,
      lng: 103.8198,
      city: "Singapore",
      country: "Singapore",
    },
    summary: "Industrial anaerobic digestion facility processing 100 tonnes daily",
    website: "https://example.com/singapore-digester",
    verified: true,
  },
  {
    id: "5",
    name: "Hanoi Organic Collection Program",
    type: "initiative",
    tags: ["organics", "reduction"],
    location: {
      lat: 21.0285,
      lng: 105.8542,
      city: "Hanoi",
      country: "Vietnam",
    },
    summary: "Door-to-door organic waste collection serving residential areas",
    verified: true,
  },
  {
    id: "6",
    name: "Kuala Lumpur Composting Hub",
    type: "facility",
    tags: ["organics"],
    location: {
      lat: 3.1390,
      lng: 101.6869,
      city: "Kuala Lumpur",
      country: "Malaysia",
    },
    summary: "Central composting facility with educational programs for schools",
    website: "https://example.com/kl-compost",
    verified: true,
  },
  {
    id: "7",
    name: "Cebu Zero Waste Coalition",
    type: "organization",
    tags: ["organics", "reduction", "policy"],
    location: {
      lat: 10.3157,
      lng: 123.8854,
      city: "Cebu",
      country: "Philippines",
    },
    summary: "Advocacy group promoting organic waste diversion policies",
    website: "https://example.com/cebu-zero-waste",
    verified: false,
  },
  {
    id: "8",
    name: "Bali Eco Warriors",
    type: "organization",
    tags: ["organics", "reuse"],
    location: {
      lat: -8.4095,
      lng: 115.1889,
      city: "Denpasar",
      country: "Indonesia",
    },
    summary: "Community organization running multiple composting centers across Bali",
    website: "https://example.com/bali-eco",
    verified: true,
  },
  {
    id: "9",
    name: "Phnom Penh Waste Solutions",
    type: "facility",
    tags: ["organics"],
    location: {
      lat: 11.5564,
      lng: 104.9282,
      city: "Phnom Penh",
      country: "Cambodia",
    },
    summary: "Mixed waste processing facility with organic separation line",
    verified: false,
  },
  {
    id: "10",
    name: "Taipei Circular Economy Hub",
    type: "initiative",
    tags: ["organics", "reduction"],
    location: {
      lat: 25.0330,
      lng: 121.5654,
      city: "Taipei",
      country: "Taiwan",
    },
    summary: "Government initiative promoting closed-loop organic waste systems",
    website: "https://example.com/taipei-circular",
    verified: true,
  },
];

// Mock Resources
export const RESOURCES: Resource[] = [
  {
    id: "1",
    slug: "back-to-earth",
    title: "Back to Earth",
    summary: "A comprehensive guide to composting organic waste at community scale",
    topics: ["organics"],
    publishDate: "2024-01-15",
    cover: "https://images.unsplash.com/photo-1572307480813-ceb0e59d8325?w=800&q=80",
    url: "https://example.com/back-to-earth",
    content: "Comprehensive content about composting methods, benefits, and implementation strategies...",
  },
  {
    id: "2",
    slug: "methane-matters",
    title: "Methane Matters: The Climate Case for Organics Diversion",
    summary: "Understanding the methane emissions from organic waste and climate impact",
    topics: ["organics", "policy"],
    publishDate: "2023-11-20",
    cover: "https://images.unsplash.com/photo-1569163139394-de4798aa62b6?w=800&q=80",
    content: "Detailed analysis of methane emissions from landfills and the climate benefits of composting...",
  },
  {
    id: "3",
    slug: "community-composting-toolkit",
    title: "Community Composting Toolkit",
    summary: "Step-by-step guide to starting a community composting program",
    topics: ["organics"],
    publishDate: "2024-02-10",
    cover: "https://images.unsplash.com/photo-1530836369250-ef72a3f5cda8?w=800&q=80",
    url: "https://example.com/toolkit",
    content: "Practical toolkit with templates, checklists, and best practices...",
  },
  {
    id: "4",
    slug: "asian-organics-landscape",
    title: "The State of Organic Waste Management in Asia",
    summary: "Regional analysis of organics management policies and practices",
    topics: ["organics", "policy"],
    publishDate: "2023-09-05",
    cover: "https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?w=800&q=80",
    content: "Comprehensive regional report covering 15 countries...",
  },
];

// Mock Campaign - Based on GAIA's Cities Methane Pledge
export const METHANE_PLEDGE_CAMPAIGN: Campaign = {
  id: "methane-pledge",
  slug: "methane-pledge",
  title: "The Cities Methane Pledge",
  summary: "When left unmanaged, organic waste releases methane, a potent greenhouse gas that traps 82.5 times more heat than carbon dioxide. Managing organic waste is one of the simplest yet most powerful ways for cities to fight climate change. By reducing methane emissions from organic waste by 70%, cities can play a pivotal role in limiting global warming to 1.5°C.",
  ctaLabel: "Sign the Cities Methane Pledge",
  ctaHref: "https://www.no-burn.org/the-cities-methane-pledge/",
  stats: [
    { label: "Heat Trapped vs CO₂", value: 82.5 },
    { label: "Methane Reduction Target", value: 70 },
    { label: "Global Warming Contribution", value: 30 },
    { label: "Required Emissions Cut by 2030", value: 45 },
  ],
  faqs: [
    {
      question: "Why does methane matter?",
      answer: "Methane is the second-largest greenhouse gas after carbon dioxide, contributing nearly 30% of global emissions. It is 82.5 times more heat-trapping than carbon dioxide over 20 years. Research shows that cutting human-caused methane emissions by 45% within this decade could prevent nearly 0.3°C of warming by 2045.",
    },
    {
      question: "How can cities reduce methane emissions?",
      answer: "Through Zero Waste initiatives, cities can achieve up to a 95% reduction in methane emissions from solid waste by 2030. In regions where municipal solid waste generates 20% of human-made methane emissions, organic waste comprises 50-80% of the total. This offers cities a dual opportunity to tackle domestic waste while significantly lowering methane emissions.",
    },
    {
      question: "What does the Cities Methane Pledge commit to?",
      answer: "Cities commit to: prioritize waste reduction throughout the supply chain; design and enforce waste segregation systems targeting 70% safe and effective recovery of organics by 2030; support infrastructure for optimal organic waste recovery through anaerobic digestion or composting; partner with farmers, businesses, and community organizations; integrate waste pickers into waste management; and encourage other local governments to join.",
    },
    {
      question: "Why should our city join?",
      answer: "Cities, local governments, and countries committed to UNFCCC goals from COP21 recognize the urgent need for action. Global greenhouse gas emissions must fall by 45% by 2030 to limit warming to 1.5°C. By implementing proper waste management practices, cities can lead the charge against climate change while protecting vulnerable communities and creating green jobs.",
    },
  ],
};

