// Auto-generated from Resources_on_Organics_Microsite CSV + Photos folder
// Re-run scripts/bulk-import-resources.py to regenerate.
import type { Resource } from './types';

export const BULK_RESOURCES: Resource[] = [
  {
    id: "bulk-01",
    slug: "01-comprehensive-guidance-for-effective-bio-waste-management-in",
    title: "Comprehensive Guidance for effective bio-waste management in the EU",
    summary: "Policy recommendations from the LIFE BIOBEST project to strengthen EU bio-waste rules, covering separate collection and recycling, markets for compost and digestate, and monitoring and enforcement.",
    topics: ["organics", "policy", "waste-management"],
    publishDate: "2024-01-01",
    cover: `${import.meta.env.BASE_URL}resources/01.png`,
    url: "https://zerowasteeurope.eu/library/comprehensive-guidance-for-effective-bio-waste-management-in-the-eu/",
    content: "The LIFE BIOBEST Comprehensive Guidance presents key policy recommendations to strengthen the EU legal framework for bio-waste management. Drawing from extensive research and stakeholder consultation, this document outlines three interconnected areas for improvement: boosting effective models for separate collection and recycling, promoting reliable markets for compost and digestate, and enhancing monitoring and enforcement of bio-waste regulations.\n\nThe guidance provides concrete policy measures to help close the gap between current practices and potential capture rates, addressing the fact that only 26% of kitchen waste is currently collected separately in the EU. It proposes specific legally binding targets, economic instruments, and monitoring requirements to support the EU\u2019s transition toward more efficient bio-waste management and healthier soils.\n\nValidated by 21 stakeholders representing 13 entities from across Europe, this document serves as a roadmap for EU policymakers working to improve bio-waste management.",
  },
  {
    id: "bulk-02",
    slug: "02-reducing-food-waste-at-local-level",
    title: "Reducing Food Waste at Local Level",
    summary: "A Zero Waste Europe and Slow Food briefing on actions municipalities can take to reduce food waste and build sustainable local food systems, with examples from across Europe.",
    topics: ["reduction", "organics", "policy"],
    publishDate: "2024-01-01",
    cover: `${import.meta.env.BASE_URL}resources/02.jpg`,
    url: "https://zerowasteeurope.eu/wp-content/uploads/2024/11/Guidance-on-food-waste-reduction-in-cities_EN.pdf",
    content: "Zero Waste Europe, together with Slow Food created a briefing, aimed at providing support to local municipalities to help reduce food waste through a holistic approach enabling the transition towards a sustainable food system.\n\nThe guidance outlines the various actions that a municipality can implement to influence food waste reduction and stimulate its sustainable local food system. The guidance highlights examples of how similar policies have been successfully implemented throughout Europe.",
  },
  {
    id: "bulk-03",
    slug: "03-fighting-climate-change-one-bio-waste-bin-at-a-time-how-the-",
    title: "Fighting climate change, one bio-waste bin at a time \u2013 how the #ForkToFarm project supports Montenegro\u2019s environmental transition",
    summary: "An interactive case study of Zero Waste Montenegro\u2019s #ForkToFarm project (2024-25), showcasing decentralized, community-driven solutions that keep organic waste out of landfills, including in the capital, Podgorica.",
    topics: ["organics", "waste-management", "climate"],
    publishDate: "2024-01-01",
    cover: `${import.meta.env.BASE_URL}resources/03.jpg`,
    url: "https://zerowasteeurope.eu/wp-content/uploads/2025/12/zwe_Dec25_ForkToFarm-case-study_Montenegro_standard1.pdf",
    content: "In this interactive case study, we try to bring to life the work led by our member Zero Waste Montenegro during the #ForkToFarm project between 2024-25.\n\nMontenegro continues to face significant pressure when it comes to its waste management, with organic waste central to this challenge as it represents around 40% of Montenegro\u2019s waste stream. Most municipalities lack operational capacity and sufficient infrastructure for proper organic waste management. But this challenge is also an opportunity, given the speed at which decentralised, community-driven solutions can be implemented at a low cost to local authorities.\n\nThis case study combines data and qualitative analysis with visual footage and content of the work done by Zero Waste Montenegro over the last 2 years to improve the amount of organic waste which is composted rather than landfilled in its partner communities, which includes the capital city, Podgorica. It showcases the first working examples of decentralised organic waste solutions and their successful impact, with videos and interviews with the leaders behind these progressive policies.",
  },
  {
    id: "bulk-04",
    slug: "04-community-led-zero-waste-systems-for-just-methane-mitigation",
    title: "Community-Led Zero Waste Systems for Just Methane Mitigation",
    summary: "Shows how community-rooted zero waste systems in cities, backed by public waste management programs, recover resources, create dignified work, and deliver measurable methane mitigation.",
    topics: ["waste-management", "climate", "organics"],
    publishDate: "2024-01-01",
    cover: `${import.meta.env.BASE_URL}resources/04.jpg`,
    url: "https://www.no-burn.org/wp-content/uploads/2025/11/EN-One-page-summary.pdf",
    content: "These cities show that community-rooted zero waste systems\u2014when supported by public waste management programs\u2014 can bring about a holistic and effective waste management system that yields both environmental and social benefits. They turn climate ambition into tangible results: recovered resources, dignified work, just transition, resilient food systems, reduced waste disposal, community ownerships and measurable methane mitigation that begins at the community level.",
  },
  {
    id: "bulk-05",
    slug: "05-building-community-resilience-and-green-jobs-through-organic",
    title: "Building Community Resilience and Green Jobs through Organic Waste: Climate Benefits and Economic Model of Just Organic Waste Management in Quezon City",
    summary: "The Barangay Payatas Zero Waste and Urban Farming Project in Quezon City shows how decentralized, community-based systems can combine organic waste management, food production, and livelihoods for just methane mitigation.",
    topics: ["organics", "waste-management", "climate"],
    publishDate: "2024-01-01",
    cover: `${import.meta.env.BASE_URL}resources/05.jpg`,
    url: "https://www.no-burn.org/wp-content/uploads/2025/11/EN-Quezon-City.pdf",
    content: "The organics diversion project in Quezon City demonstrates how decentralized, community-based waste systems can advance both climate action and social inclusion. The Barangay Payatas Zero Waste and Urban Farming Project, launched in 2024, stands as a model of how cities can integrate organic waste management, food production, and livelihood creation to achieve just and sustainable methane mitigation.",
  },
  {
    id: "bulk-06",
    slug: "06-building-community-resilience-and-green-jobs-through-organic",
    title: "Building Community Resilience and Green Jobs through Organic Waste: Climate Benefits and Economic Model of Just Organic Waste Management in Buenos Aires City",
    summary: "The Recuperadores Urbanos del Oeste (RUO) cooperative shows how waste picker-led waste management creates green jobs and builds climate resilience, and how scaling composting to 80% of organics would boost methane reductions nearly fivefold.",
    topics: ["organics", "waste-management", "climate"],
    publishDate: "2024-01-01",
    cover: `${import.meta.env.BASE_URL}resources/06.jpg`,
    url: "https://www.no-burn.org/wp-content/uploads/2025/11/Building-Community-Resilience-and-Green-Jobs-through-Organic-Waste_Buenos-Aires.pdf",
    content: "The Recuperadores Urbanos del Oeste (RUO) cooperative exemplifies how waste picker-led waste management can generate green jobs, strengthen climate resilience, and build social cohesion while supporting the city\u2019s ambitious landfill diversion and climate goals. Scaling composting from BAU scenario to 80 percent of organics would increase methane reductions nearly fivefold. 4 2 2 Strengthening policies that secure land, equipment, finance, and fair compensation for waste picker cooperatives will be essential to replicate this model. By expanding waste picker-led organics management within its zero waste framework, Buenos Aires can achieve its climate targets while advancing a just transition rooted in the community.",
  },
  {
    id: "bulk-07",
    slug: "07-building-community-resilience-and-green-jobs-through-organic",
    title: "Building Community Resilience and Green Jobs through Organic Waste: Climate Benefits and Economic Model of Just Organic Waste Management in Accra",
    summary: "The Green Africa Youth Organization (GAYO) in Accra shows how a decentralized, community-led model for organic waste diversion can create green jobs, reduce methane emissions, and strengthen local governance.",
    topics: ["organics", "waste-management", "climate"],
    publishDate: "2024-01-01",
    cover: `${import.meta.env.BASE_URL}resources/07.jpg`,
    url: "https://www.no-burn.org/wp-content/uploads/2025/11/Building-Community-Resilience-and-Green-Jobs-through-Organic-Waste_Accra.pdf",
    content: "Accra is paving a path toward climate resilience and social equity through community-led zero waste initiatives. The Green Africa Youth Organization (GAYO) has pioneered a decentralized waste management model that demonstrates how organic waste diversion can create green jobs, reduce methane emissions, and strengthen local governance.",
  },
  {
    id: "bulk-08",
    slug: "08-municipal-strategies-for-organic-waste-a-toolkit-to-cut-meth",
    title: "Municipal Strategies for Organic Waste: A Toolkit to Cut Methane Emissions",
    summary: "The first in GAIA\u2019s Technical Guidance Series for Policymakers and Financiers, introducing six strategies municipalities can use to keep organic waste out of landfills and cut methane emissions.",
    topics: ["organics", "climate", "waste-management", "policy"],
    publishDate: "2024-01-01",
    cover: `${import.meta.env.BASE_URL}resources/08.jpg`,
    url: "https://www.no-burn.org/wp-content/uploads/2025/08/Municipal-Strategies-for-Organic-Waste-A-Toolkit-to-Cut-Methane-Emissions.pdf",
    content: "Municipal Strategies for Organic Waste: A Toolkit to Cut Methane Emissions is the 1st of the GAIA Technical Guidance Series for Policymakers and Financiers on Fast Action on Waste and Methane. Following commitments within the Global Methane Pledge and the COP29 Declaration to Reduce Methane from Organic Waste (ROW declaration), signatory countries have pledged to significantly reduce waste methane emissions by 2030. While this will pose an increase of political and financial resources driven towards the waste sector, there is a need to ensure the implementation of measures to reduce methane emissions is aligned with the Environmental Justice Principles for Fast Action on Waste and Methane.\n\nThis toolkit introduces six key strategies to help municipalities reduce methane emissions from organic waste: animal feed, composting, vermicomposting, anaerobic digestion, black soldier fly processing, and landfill biocovers. The primary objective is to prevent organic waste from reaching landfills by prioritizing diversion and resource recovery.",
  },
  {
    id: "bulk-09",
    slug: "09-cop-29-row-declaration",
    title: "COP 29 ROW Declaration",
    summary: "A COP29 declaration in which national governments commit to reducing methane from organic waste, including by building waste measures into their NDCs and scaling up finance.",
    topics: ["policy", "climate", "organics"],
    publishDate: "2024-01-01",
    cover: `${import.meta.env.BASE_URL}resources/09.png`,
    url: "https://cop29.az/en/pages/cop29-declaration-on-reducing-methane-from-organic-waste",
    content: "A COP29 declaration in which national governments commit to reducing methane from organic waste, including by building waste measures into their NDCs and scaling up finance.",
  },
  {
    id: "bulk-10",
    slug: "10-cutting-emissions-through-zero-waste-food-systems",
    title: "Cutting Emissions Through Zero Waste Food Systems",
    summary: "Highlights how Fundacion Basura in Chile and Gita Pertiwi in Indonesia tackle food waste, sharing best practices and lessons to inspire other communities to act.",
    topics: ["organics", "reduction", "climate"],
    publishDate: "2024-01-01",
    cover: `${import.meta.env.BASE_URL}resources/10.jpg`,
    url: "https://www.no-burn.org/wp-content/uploads/2024/09/Cutting-Methane-Emissions-through-Zero-Food-Waste-Systems-ENG-.pdf",
    content: "Food waste and food loss is a pressing global issue with significant social, economic, and environmental implications if unaddressed. With increased awareness of its role in a zero waste system and the numerous projects and initiatives to combat food waste worldwide, it remains overlooked and often takes a backseat in the array of waste issues that needs urgent attention.\n\nThis publication highlights the successful interventions of Fundacion Basura in Chile and Gita Pertiwi in Indonesia addressing food waste across different settings. It shows best practices, innovative approaches, and lessons learned from each project area. Through the tangible impacts and actionable examples, it aims to inspire other communities and stakeholders to take action against food waste on a global scale.",
  },
  {
    id: "bulk-11",
    slug: "11-a-key-to-rapid-methane-reductions-keeping-organic-waste-from",
    title: "A Key to Rapid Methane Reductions: Keeping Organic Waste From Landfills",
    summary: "Explains why keeping organic waste out of landfills is one of the fastest and most affordable ways to cut methane, since landfilled organics drive most waste sector methane emissions.",
    topics: ["organics", "climate"],
    publishDate: "2024-01-01",
    cover: `${import.meta.env.BASE_URL}resources/11.jpg`,
    url: "https://www.no-burn.org/wp-content/uploads/2022/11/GAIA_White_Paper_A_Key_to_Rapid_Methane_Reductions_FINAL.pdf",
    content: "Waste is the third largest source of methane emissions, a greenhouse gas over 80 times as potent as CO2. Most waste sector methane emissions come from landfilling organic waste. This paper discusses how diverting organic waste from landfill is one of the fastest and most affordable ways to lower methane emissions.",
  },
  {
    id: "bulk-12",
    slug: "12-back-to-earth-composting-for-various-contexts",
    title: "Back to Earth: Composting for various contexts",
    summary: "An illustrated, easy-to-follow composting guide for any setting, from backyards to high-rise apartments, showing how anyone can ease the burden on landfills and cut emissions.",
    topics: ["organics", "waste-management", "climate"],
    publishDate: "2024-01-01",
    cover: `${import.meta.env.BASE_URL}resources/12.jpg`,
    url: "https://www.no-burn.org/wp-content/uploads/2022/01/Back-to-Earth-Organics-Manual_Spread.pdf",
    content: "With organics making up more than 50% of solid waste in Asia, managing this waste stream will have a huge impact on waste management and the reduction of methane emissions.\n\nWith superb illustrations and easy-to-follow instructions, \u201cBack to Earth\u201d encourages people to explore every facet of composting: whether in a sprawling backyard or in a limited space such as a high-rise apartment, composting can be customized to suit any situation.\n\nThe most important message, however, is that composting is a simple and yet effective step anyone can take to help alleviate the burden on our landfills, replenish soil nutrients, and reduce carbon and methane emissions.",
  },
  {
    id: "bulk-13",
    slug: "13-environmental-justice-principles-for-fast-action-on-waste-an",
    title: "Environmental Justice Principles for Fast Action on Waste and Methane",
    summary: "A framework setting out five environmental justice principles for the waste sector, with guidance and NDC checklists to help decision-makers build justice into national methane reduction plans.",
    topics: ["policy", "climate"],
    publishDate: "2024-01-01",
    cover: `${import.meta.env.BASE_URL}resources/13.jpg`,
    url: "https://www.no-burn.org/wp-content/uploads/2024/09/Environmental-Justice-Principles.pdf",
    content: "Environmental justice is key to ensuring climate solutions that are fair, just, and sustainable in the future. Up until now, and despite its importance, there has been no central set of values and principles to guide decision-makers in order to ensure that the right steps are being taken to incorporate justice into national plans for methane reduction. The Framework includes a vision for systems change towards zero waste, climate justice, and quick action on methane reduction. Furthermore, it outlines five EJ principles for the waste sector. It is also complemented with guidance for policymakers and checklists for NDCs that are anchored to the five principles. Successful implementation of organic waste diversion in line with EJ principles builds community, waste worker, and local government buy-in and demonstrates the practical effectiveness of these strategies, including important co-benefits in livelihoods and environmental health.",
  },
  {
    id: "bulk-14",
    slug: "14-climate-finance-for-zero-waste-and-just-transition-driving-i",
    title: "Climate Finance for Zero Waste and Just Transition: Driving Implementation towards Equitable and Just Solutions in the Waste Sector",
    summary: "Shows that the waste sector produces nearly 20% of global methane emissions yet receives under 1.5% of climate finance, and calls for redirecting funds to zero waste and a just transition.",
    topics: ["climate", "policy", "false-solutions"],
    publishDate: "2024-01-01",
    cover: `${import.meta.env.BASE_URL}resources/14.jpg`,
    url: "https://www.no-burn.org/wp-content/uploads/2025/11/Climate-Finance-for-Zero-Waste-and-Just-Transition.pdf",
    content: "The waste sector is one of the world\u2019s most powerful but overlooked levers for climate action and social justice. It contributes nearly 20 percent of global methane emissions, yet received less than 1.5 percent of climate finance in 2023 (Climate Policy Initiative [CPI], 2025a, p.4). Ninety-nine percent of it goes to waste-to-energy (WTE) projects and only 1 percent dedicated to organic waste management (Climate Policy Initiative [CPI], 2023a, p. 16). International climate finance for waste management is also primarily supported by private finance and using debt-inducing instruments (CPI, 2025a, p. 22).\n\nAt The Implementation COP in Bel\u00e9m, the world faces a defining test. COP30 must prove that climate finance can drive both rapid mitigation and tangible improvements in people\u2019s lives. For the waste sector, this means redirecting finance toward zero waste solutions and Just Transition that create jobs, improve health, and strengthen local economies. Investing in waste pickers, informal workers, and communities is not charity; it is a multiplier strategy that brings millions of workers into the climate system, where small investments yield disproportionate and sustained impacts. This approach will aid us to achieve our climate target and build service-based systems that leave no one behind.",
  },
  {
    id: "bulk-15",
    slug: "15-managing-organic-waste-with-waste-pickers-a-briefing-for-pol",
    title: "Managing Organic Waste with Waste Pickers \u2013 A briefing for policy makers",
    summary: "A GAIA and International Alliance of Waste Pickers briefing with recommendations for integrating waste pickers into organic waste management to cut methane and support their livelihoods.",
    topics: ["organics", "waste-management", "policy", "climate"],
    publishDate: "2024-01-01",
    cover: `${import.meta.env.BASE_URL}resources/15.jpg`,
    url: "https://www.no-burn.org/wp-content/uploads/2026/05/EN-Managing-organics-with-waste-pickers.pdf",
    content: "Waste pickers play a critical role in climate action, methane reduction, and sustainable waste management, yet their contributions are often overlooked in public policy. This briefing from the Global Alliance for Incinerator Alternatives (GAIA) highlights how integrating waste pickers into formal waste management systems can improve environmental outcomes, strengthen local economies, and advance environmental justice.\n\n\"Managing Organics with Waste Pickers: A Briefing for Policymakers,\" co-released by GAIA and the International Alliance of Waste Pickers, examines how waste pickers\u2014estimated at 15 to 20 million workers worldwide\u2014are increasingly leading organic waste management efforts. By diverting food scraps and organic materials from landfills, waste pickers help reduce methane emissions, one of the most potent greenhouse gases driving climate change.\n\nThe report provides recommendations for policymakers seeking to build inclusive, community-based waste management systems that support waste picker livelihoods while advancing climate and zero waste goals.",
  },
  {
    id: "bulk-16",
    slug: "16-addressing-landfill-methane-emissions-with-environmental-jus",
    title: "Addressing Landfill Methane Emissions with Environmental Justice",
    summary: "Outlines the risks of business-as-usual approaches to landfill methane and makes the case for a justice-centered response, drawing on evidence of what works in landfill closure and organics management.",
    topics: ["climate", "waste-management", "false-solutions"],
    publishDate: "2024-01-01",
    cover: `${import.meta.env.BASE_URL}resources/16.jpg`,
    url: "https://www.no-burn.org/wp-content/uploads/2025/09/Addressing-Landfill-Methane-Emissions-with-Environmental-Justice.pdf",
    content: "As governments respond to the growing pressure to reduce methane emissions under the Global Methane Pledge and broader climate goals, landfills and dumpsites have emerged as a critical point of intervention for climate mitigation. These sites, many of which are uncontrolled, decades old, and located near marginalized communities, pose serious environmental, social, and public health risks. Methane emissions, groundwater contamination, fire hazards, and human exposure to toxic pollutants all persist long after waste disposal ends. Yet while political momentum for methane reduction is increasing, too many proposed interventions focus narrowly on technical fixes that risk deepening social and environmental inequities.\n\nThis report outlines the risks of business-as-usual (BAU) approaches to landfill methane mitigation and makes the case for a sustainable, justice-centered response. It draws on international evidence, current policy trends, and community experience to identify what works, and what doesn\u2019t, when it comes to landfill closure and organics management.",
  },
  {
    id: "bulk-17",
    slug: "17-ramping-up-ambition-on-waste-methane-and-just-transition-in-",
    title: "Ramping Up Ambition on Waste Methane and Just Transition in Indonesia: Recommendations for Indonesia\u2019s Second NDC",
    summary: "Recommendations for Indonesia\u2019s Second NDC, scheduled for 2025, to raise ambition on waste sector emissions and mobilize climate finance for methane reduction.",
    topics: ["policy", "climate"],
    publishDate: "2024-01-01",
    cover: `${import.meta.env.BASE_URL}resources/17.jpg`,
    url: "https://www.no-burn.org/wp-content/uploads/2025/05/Second-NDC-Indonesia-1.pdf",
    content: "In 2025, the Government of Indonesia (GoI) is scheduled to submit its Second Nationally Determined Contribution (NDC). This presents a crucial opportunity for the government to enhance its ambition regarding emissions mitigation in the waste sector and to mobilize significant climate finance specifically for methane emissions.",
  },
  {
    id: "bulk-18",
    slug: "18-gaia-s-ndc-checklist-guidance-on-integrating-waste-and-metha",
    title: "GAIA\u2019s NDC Checklist: Guidance on integrating waste and methane reduction into the NDCs 3.0 in alignment with Environmental Justice Principles",
    summary: "A checklist for integrating waste and methane reduction into NDCs 3.0, framing zero waste strategies like separate collection and composting as core climate and justice solutions.",
    topics: ["policy", "climate", "reduction"],
    publishDate: "2024-01-01",
    cover: `${import.meta.env.BASE_URL}resources/18.jpg`,
    url: "https://www.no-burn.org/wp-content/uploads/2024/11/GAIAs-NDC-Checklist.pdf",
    content: "Zero waste solutions are a fundamental part of the efforts to reduce greenhouse gas emissions, build resilience and ensure justice and equity at the heart of the transition to a sustainable planet. These are versatile strategies that aim to continually reduce waste through source reduction, separate collection, composting and recycling, ensuring that all discarded materials are safely and sustainably returned to nature or manufacturing. Most importantly, zero waste strategies help societies produce and consume goods while respecting resource scarcity, planetary boundaries and the rights of communities. Practicing zero waste means moving toward a world in which all materials are used to their utmost potential, nothing goes to waste, and the needs of people\u2014workers and communities\u2014are met through a system that protects and does no harm to the environment.",
  },
  {
    id: "bulk-19",
    slug: "19-nourishing-communities-gita-pertiwi-s-justice-centered-food-",
    title: "Nourishing Communities: Gita Pertiwi\u2019s Justice-Centered Food Sharing Model in Surakarta, Indonesia",
    summary: "Profiles Gita Pertiwi\u2019s justice-centered food sharing model in Surakarta, set against Indonesia\u2019s status as Southeast Asia\u2019s largest food waste producer.",
    topics: ["reduction", "organics"],
    publishDate: "2024-01-01",
    cover: `${import.meta.env.BASE_URL}resources/19.jpg`,
    url: "https://www.no-burn.org/wp-content/uploads/2024/11/Nourishing-Communities-Gita-Pertiwis-Justice-Centered-Food-Sharing-Model-in-Surakarta-Indonesia.pdf",
    content: "According to the UN Environment Programme\u2019s Food Waste Index Report 2021, Indonesia is the largest food waste producer in Southeast Asia. The report found that around 20.93 million tons of food waste are produced annually in Indonesia. According to data from the Ministry of Environment and Forestry of Indonesia (Kementerian Lingkungan Hidup dan Kehutanan), in 2023, Indonesia\u2019s food waste accounted for 40.73% of the total waste composition, or approximately 13,743,661 tons per year.",
  },
  {
    id: "bulk-20",
    slug: "20-climate-finance-from-harmful-to-impactful",
    title: "Climate Finance: From Harmful to Impactful",
    summary: "Calls for moving waste sector climate finance away from waste-to-energy incineration, which receives 99% of the sector\u2019s methane reduction funding despite fueling air pollution, debt, and lost livelihoods.",
    topics: ["false-solutions", "climate", "policy"],
    publishDate: "2024-01-01",
    cover: `${import.meta.env.BASE_URL}resources/20.jpeg`,
    url: "https://www.no-burn.org/wp-content/uploads/2024/10/Climate-Finance.pdf",
    content: "Climate finance needs to move from harmful to impactful - also in the waste sector, where 99% of climate finance for methane reduction goes to waste-to-energy incineration, a highly problematic industry responsible for climate change, air pollution, indebtedness of global south countries, and loss of livelihoods in vulnerable communities.",
  },
  {
    id: "bulk-21",
    slug: "21-methane-matters-towards-a-global-methane-agreement",
    title: "Methane Matters: Towards a Global Methane Agreement",
    summary: "Methane emissions must fall 45% this decade to keep warming below 1.5\u00b0C. This report shows how to cut them in the three top emitting sectors: energy, agriculture, and waste.",
    topics: ["climate", "policy"],
    publishDate: "2024-01-01",
    cover: `${import.meta.env.BASE_URL}resources/21.jpg`,
    url: "https://www.no-burn.org/wp-content/uploads/2022/11/CM-Report-Layout-Methane-Matters-Nove-2022-WEB-Spread-pg.pdf",
    content: "To keep warming below 1.5 degrees Celsius, methane emissions must be cut by 45% this decade. Read more about how emissions can be cut in the three top emitting sectors: energy, agriculture, and waste .",
  },
  {
    id: "bulk-22",
    slug: "22-methane-matters-a-comprehensive-approach-to-methane-mitigati",
    title: "Methane Matters: A Comprehensive Approach to Methane Mitigation",
    summary: "Lays out the most actionable steps governments can take to cut methane, showing that waste prevention and source separation of organics could reduce solid waste methane by up to 95% by 2030.",
    topics: ["climate", "policy", "reduction", "organics"],
    publishDate: "2024-01-01",
    cover: `${import.meta.env.BASE_URL}resources/22.jpg`,
    url: "https://www.no-burn.org/wp-content/uploads/2022/03/METHANE-MATTERS.pdf",
    content: "This report highlights the most actionable steps governments can take to reduce methane emissions. We found that by tackling the waste sector, governments will get fast results using some of the easiest and most affordable methane reduction strategies available. Waste prevention, source-separation of organic discards, and other methods can reduce solid waste methane emissions by as much as 95% by 2030.",
  },
  {
    id: "bulk-23",
    slug: "23-waste-pickers-and-climate-change",
    title: "Waste Pickers and Climate Change",
    summary: "Shows how waste pickers cut greenhouse gas emissions through recovery and recycling, and how waste-to-energy technologies are undermining their work.",
    topics: ["climate", "waste-management", "false-solutions"],
    publishDate: "2024-01-01",
    cover: `${import.meta.env.BASE_URL}resources/23.jpg`,
    url: "https://www.no-burn.org/wp-content/uploads/2021/11/wastepickers-CC-EN.pdf",
    content: "Wastepickers are workers in the informal economy who recover recyclable materials from waste. They are invisible entrepreneurs on the frontlines of the fight against climate change, earning livelihoods from recovery and recycling, reducing demand for natural resources, and reducing greenhouse gas emissions. Yet their successes are being undermined by \u201cwaste-to-energy\u201d technologies.",
  },
  {
    id: "bulk-24",
    slug: "24-seven-key-solutions-to-landfill-methane",
    title: "Seven Key Solutions to Landfill Methane",
    summary: "A fact sheet on how zero waste solutions that keep organic waste out of landfills can cut methane, protect the climate, and improve food systems.",
    topics: ["climate", "organics"],
    publishDate: "2024-01-01",
    cover: `${import.meta.env.BASE_URL}resources/24.jpg`,
    url: "https://www.no-burn.org/wp-content/uploads/2021/11/Seven-Key-Solutions-to-Landfill-Methane_May-18-2021.pdf",
    content: "A new United Nations report shows that we must tackle methane emissions to keep planetary warming under control. Methane is a more potent greenhouse gas than carbon dioxide, and much of it comes from organic waste in landfills. The good news is that we can solve this problem simply and easily through zero waste. By preventing organic waste from being landfilled we can protect our climate AND improve our food systems. Read our fact sheet and blog for details.",
  },
  {
    id: "bulk-25",
    slug: "25-zero-waste-city-manual-a-toolkit-to-establish-city-and-commu",
    title: "Zero Waste City Manual: A toolkit to establish city and community zero waste systems",
    summary: "A practical toolkit from CAG, based on work with the Greater Chennai Corporation, for setting up zone-level zero waste systems in Indian cities that other cities can adapt.",
    topics: ["waste-management"],
    publishDate: "2024-01-01",
    cover: `${import.meta.env.BASE_URL}resources/25.jpg`,
    url: "https://www.no-burn.org/wp-content/uploads/2021/11/ZWC-Manual_20200725-1.pdf",
    content: "The Zero Waste City Manual: A toolkit to establish city and community Zero Waste systems by GAIA member Citizen consumer and civic Action Group (CAG) presents a practicable plan for municipalities to process waste, aggregate recyclables and domestic hazardous waste at the zone level, and leverage the private formal and informal waste networks in all Indian cities. Prepared based on ground experience working with the Greater Chennai Corporation to transition from a centralized waste to a Zero Waste system, the manual can be adapted to other cities based on their local context.",
  },
  {
    id: "bulk-26",
    slug: "26-zero-waste-to-zero-emissions",
    title: "Zero Waste to Zero Emissions",
    summary: "Drawing on eight city case studies, this GAIA report shows that zero waste strategies can cut waste-related emissions by an average of 84% while creating green jobs.",
    topics: ["climate", "reduction", "organics", "false-solutions"],
    publishDate: "2024-01-01",
    cover: `${import.meta.env.BASE_URL}resources/26.jpg`,
    url: "https://www.no-burn.org/wp-content/uploads/2022/11/zero-waste-to-zero-emissions_full-report.pdf",
    content: "The report titled \"Zero Waste to Zero Emissions: How Reducing Waste is a Climate Gamechanger\" by GAIA highlights how municipal zero waste strategies serve as critical, rapid solutions to the climate crisis. It reveals that the waste sector accounts for roughly 20% of global anthropogenic methane emissions, making organic waste source separation and composting crucial tools for immediate greenhouse gas reductions). By analyzing eight global city case studies, the publication demonstrates that implementing zero waste models can slash waste-related emissions by an average of 84%. The text heavily discourages waste combustion and incineration, proving that these expensive practices lock municipalities into high greenhouse gas emissions while threatening local air quality. Ultimately, the document positions zero waste as a cost-effective vehicle for climate adaptation, showing that these programs stimulate green job creation and improve soil resilience.",
  },
  {
    id: "bulk-27",
    slug: "27-food-systems-a-recipe-for-food-waste-prevention",
    title: "Food systems: a recipe for food waste prevention",
    summary: "A Zero Waste Europe policy briefing arguing that tackling food waste requires a strategy covering the whole food system, from crop to compost.",
    topics: ["reduction", "organics", "policy"],
    publishDate: "2024-01-01",
    cover: `${import.meta.env.BASE_URL}resources/27.jpg`,
    url: "https://zerowasteeurope.eu/wp-content/uploads/2019/11/zero_waste_europe_policy_briefing_food_systems_en.pdf",
    content: "Food Waste is an economic, environmental, social and ethical issue. The strategy to tackle it has to cover the whole food system from crop to compost. Read the Zero Waste Europe Policy Briefing on Food Systems.",
  },
  {
    id: "bulk-28",
    slug: "28-feeding-communities-cutting-emissions-how-greeners-action-tu",
    title: "Feeding Communities, Cutting Emissions: How Greeners Action Turn Wet Market Surplus into Social Impact",
    summary: "How Greeners Action turns wet market food surplus into support for communities while cutting methane emissions.",
    topics: ["reduction", "organics", "climate"],
    publishDate: "2024-01-01",
    cover: `${import.meta.env.BASE_URL}resources/28.jpg`,
    url: "https://www.no-burn.org/wp-content/uploads/2026/03/EN-Greeners-Action_Feeding-Communities-Cutting-Emissions-Impact.pdf",
    content: "Good food shouldn\u2019t go to waste while people go without. This story from \u7da0\u9818\u884c\u52d5 Greeners Action shows what\u2019s possible when communities take the lead\u2014turning surplus into support, cutting methane emissions, and quietly proving that climate solutions can be practical, local, and deeply human.",
  },
  {
    id: "bulk-29",
    slug: "29-separation-at-source",
    title: "Separation at Source",
    summary: "Presents 12 successful source separation cases across five regions, from Tilos Island to Bengaluru, with organic waste diversion rates of up to 100%.",
    topics: ["waste-management", "organics"],
    publishDate: "2024-01-01",
    cover: `${import.meta.env.BASE_URL}resources/29.jpg`,
    url: "https://www.no-burn.org/wp-content/uploads/2026/09/Separation-at-Source-S@S-12-Real-World-Zero-Waste-Practices-That-Work-2.pdf",
    content: "This publication presents 12 diverse successful cases from five regions: Africa (Tanzania), Asia (India, The Philippines), Europe (Greece, Slovenia, Italy), North America (USA), and Latin America (Costa Rica). The communities featured range in scale, from Tilos Island with a permanent population of 700 residents, to megacities such as Bengaluru, where the zero waste systems reach approximately 2 million people. Across these jurisdictions, source separation rates vary according to local mandates and frameworks, ranging from 30-33% organic waste diversion in Portland to outstanding rates of 80- 95% in places such as Varkala, San Fernando, and Dar es Salaam, and reaching 100% in Tilos Island.",
  },
  {
    id: "bulk-30",
    slug: "30-financing-zero-waste-practical-guidance-for-immediate-action",
    title: "Financing Zero Waste - Practical Guidance for Immediate Action by local and National governments",
    summary: "Practical guidance to help governments finance zero waste systems that prevent waste, expand reuse, and maximize recycling and composting despite tight budgets and capacity gaps.",
    topics: ["policy", "waste-management", "reduction", "reuse"],
    publishDate: "2024-01-01",
    cover: `${import.meta.env.BASE_URL}resources/30.jpg`,
    url: "https://www.no-burn.org/wp-content/uploads/2026/09/Financing-Zero-Waste-ZWCF.pdf",
    content: "Local governments face significant financial, institutional, and operational challenges in delivering waste management services, including constrained budgets, competing public-service priorities, political pressures, infrastructure gaps, and limited technical capacity. At the same time, local governments have a critical role to play in building waste management systems that prevent waste, expand reuse and repair, ensure source separation and collection of recyclable and organic materials, and maximize recycling and composting while reducing reliance on landfilling and incineration.",
  },
  {
    id: "bulk-31",
    slug: "31-financing-zero-waste-a-high-level-synthesis-report",
    title: "Financing Zero Waste - A high level synthesis report",
    summary: "A high-level synthesis of the Zero Waste Finance Guide series, bringing together the local and national government guides to outline a complementary strategy for financing zero waste.",
    topics: ["policy", "waste-management"],
    publishDate: "2024-01-01",
    cover: `${import.meta.env.BASE_URL}resources/31.jpg`,
    url: "https://www.no-burn.org/wp-content/uploads/2026/09/Financing-Zero-Waste-ZWCF-Synthesis-.pdf",
    content: "This publication is a high-level synthesis of the Zero Waste Finance Guide series, drawing on companion guidance for local and national governments to address a central challenge: financing the transition to zero waste requires more than securing capital for new infrastructure. It requires an approach that recognizes the wider public value of waste management, addresses the structural barriers that limit local implementation, and aligns national policy and fiscal frameworks with the realities of municipal service delivery. This synthesis brings together the findings of the Local and National Government Guides to identify common financing challenges and outline a complementary strategy for addressing them.",
  },
];
